{% set name = "sqlalchemy-drill" %}
{% set version = "1.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sqlalchemy_drill-{{ version }}.tar.gz
  sha256: 17760cbb49db233561d0f615477ea20b753348f12a03dc8cc1f34ef12a0e79ac

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - ijson
    - requests
    - sqlalchemy

test:
  imports:
    - sqlalchemy_drill
    - sqlalchemy_drill.drilldbapi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/JohnOmernik/sqlalchemy-drill
  summary: Apache Drill for SQLAlchemy
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/JohnOmernik/sqlalchemy-drill

extra:
  recipe-maintainers:
    - xylar
