{% set name = "sqlalchemy-drill" %}
{% set version = "1.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlalchemy_drill-{{ version }}.tar.gz
  sha256: 8a167af388ef0530fe79adae1c547fb4b651615d300c106ff659c12e2688aa57

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - ijson
    - requests
    - sqlalchemy

test:
  imports:
    - sqlalchemy_drill
    - sqlalchemy_drill.drilldbapi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JohnOmernik/sqlalchemy-drill
  summary: Apache Drill for SQLAlchemy
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/JohnOmernik/sqlalchemy-drill

extra:
  recipe-maintainers:
    - xylar
